extends:
  - airbnb-base
  - eslint:recommended
  - ../.eslintrc.yml

env:
  node: true

rules:
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
  no-console:
    - warn
    - allow:
        - warn
        - error
        - info
  prefer-promise-reject-errors:
    - off
  import/no-import-module-exports:
    - off
  import/no-relative-packages:
    - off

overrides:
  - files:
      - ./src/db/seeds/**/*
      - ./src/db/seed-data/**/*
    rules:
      no-console:
        - off
      max-len:
        - off
  - files:
      - ./src/packages/**/*
    rules:
      import/no-cycle:
        - off
  - files:
      - knexfile.js
    rules:
      'import/no-default-export':
        - off
